AWSTemplateFormatVersion: '2010-09-09'
Description: Templates under onetime templates
Parameters:
  Env:
    Type: String
    Description: 'environment (uppercase only), ex: QAS, PRD, DEV'
    Default: DEV
  AppEnv:
    Type: String
    Description: 'application environment (lowercase only), ex: qas, prd, dev'
    Default: dev
  Org:
    Type: String
    Description: 'organization (lowercase only), ex: belc (belcorp)'
    Default: belc
  MyTemplateUploadsBucket:
    Type: String
    Description: S3 bucket for referenced templates
  MyVPCSubnetIDsA:
    Type: AWS::EC2::Subnet::Id
    Description: The list of SubnetIds in your Virtual Private Cloud (VPC)
  MyVPCSubnetIDsB:
    Type: AWS::EC2::Subnet::Id
    Description: The list of SubnetIds in your Virtual Private Cloud (VPC)
  MyVPCSecurityGroupIDs:
    Type: AWS::EC2::SecurityGroup::Id
    Description: The list of SubnetIds in your Virtual Private Cloud (VPC)
Resources:
  MloLambdaFunctions:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        Fn::Sub: https://s3.amazonaws.com/${Org}-bigdata-models-dlk-${AppEnv}/deploy/lambdas.yaml
      Parameters:
        Env:
          Ref: Env
        AppEnv:
          Ref: AppEnv
        TemplateUploadsBucket:
          Ref: MyTemplateUploadsBucket
        VPCSubnetIDsA:
          Ref: MyVPCSubnetIDsA
        VPCSubnetIDsB:
          Ref: MyVPCSubnetIDsB
        VPCSecurityGroupIDs:
          Ref: MyVPCSecurityGroupIDs
  MloStateMachineRes:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        Fn::Sub: https://s3.amazonaws.com/${Org}-bigdata-models-dlk-${AppEnv}/deploy/step_function.yaml
      Parameters:
        Env:
          Ref: Env    
        TemplateUploadsBucket:
          Ref: MyTemplateUploadsBucket