AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Step Functions for the Machine Learning Orchestrator
Parameters:
  Env:
    Default: DEV
    Type: String
    Description: 'environment (uppercase only), ex: DEV, QAS, PRD'
  TemplateUploadsBucket:
    Default: belc-bigdata-models-dlk-dev
    Type: String
    Description: S3 bucket for referenced templates
Resources:
  StateMachineRes:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName:
        Fn::Sub: SF-MLO-${Env}
      RoleArn:
        Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/IAM-MLO-LambdaExec-${Env}
      DefinitionString:
        !Sub |
        {
          "Comment": "Step to Submit request to Algorithm API",
          "StartAt": "SubmitRequest",
          "States": {
            "SubmitRequest": {
              "Type": "Task",
              "Resource": "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:Lambda-MLO-SubmitRequests-${Env}",
              "Next": "CheckProcessRequestStatus"
            },
            "CheckProcessRequestStatus": {
              "Type": "Choice",
              "Choices": [
                {
                  "Variable":"$.request_status",
                  "StringEquals":"REQUESTED",
                  "Next":"WaitForProcess"
                },
                {
                  "Variable":"$.request_status",
                  "StringEquals":"FAILED",
                  "Next":"PostProcessingStep"
                }
              ],
              "Default":"PostProcessingStep"
            },
            "WaitForProcess":{
              "Type":"Wait",
              "SecondsPath":"$.info.avg_wait_time",
              "Next":"CheckProcessStatus"
            },
            "CheckProcessStatus":{
              "Type":"Task",
              "Resource":"arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:Lambda-MLO-CheckStatus-${Env}",
              "Next":"ChoiceOnProcessStatus"
            },
            "ChoiceOnProcessStatus":{
              "Type":"Choice",
              "Choices":[
                {
                  "Variable":"$.process_info.status",
                  "StringEquals":"COMPLETED",
                  "Next": "PostProcessingStep"
                },
                {
                  "Variable":"$.process_info.status",
                  "StringEquals":"FAILED",
                  "Next": "PostProcessingStep" 
                },
                {
                  "Variable":"$.process_info.status",
                  "StringEquals":"RUNNING",
                  "Next": "WaitForProcess"
                }
              ]
            },
            "PostProcessingStep":{
              "Type": "Task",
              "Resource": "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:Lambda-MLO-PostProcessing-${Env}",
              "End": true
            }
          }
        }
      