request_status = "request_status"
process_status = "process_status"
uuid = "uuid"
post_request_status = 200
country = "country"
campaign = "campaign"
env = "env"
message_type = "message_type"
process_type = "process_type"

process_info = "process_info"
stage = "stage"
created_at = "created_at"
failure_reason = "failure_reason"
avg_wait_time = "avg_wait_time"

status = "status"
init_process = "init_process"
timestamp_string = "timestamp"
info = "info"
algorithm = "algorithm"
list_process = "Process"
none_failure_reason = "None"
mlo_uuid = "mlo_uuid"
endpoint = "endpoint"
payload = "payload"
